FROM golang:1.16

RUN mkdir /backend
WORKDIR /backend

# COPY go.mod ./../../backend/go.mod
# COPY go.sum ./../../backend/go.sum
# RUN go mod download
COPY ./backend/go.mod /backend/go.mod
COPY ./backend/go.sum /backend/go.sum
RUN go mod download

# COPY ./../../backend /backend
COPY ./backend /backend

EXPOSE 8080