version: '3'
services:
  db:
    container_name: blog-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ./backend/server/postgres/data:/var/lib/postgresql/data
    ports:
      - 3306:3306

  backend:
    container_name: blog-server
    image: kawada-tech-blog-server-dev
    build:
      dockerfile: backend/Dockerfile.development
      context: .
    tty: true
    stdin_open: true
    command: bash -c "go run main.go"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    ports:
      - 8080:8080
    
  frontend:
    container_name: blog-front
    image: kawada-tech-blog-front-dev
    build:
      dockerfile: frontend/Dockerfile.development
      context: .
    tty: true
    stdin_open: true
    command: bash -c " npm run dev"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend
      - db

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    command: ['server', '/data', '--console-address', ':9001']
    volumes:
      - ./backend/server/minio/data:/data:delegated
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    restart: always
    depends_on:
      - db
      - backend
      - frontend