version: '3'
services:
  db:
    image: postgres
    container_name: blog-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ./backend/server/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    image: kawada-tech-blog-server-dev
    container_name: blog-server
    build:
      dockerfile: backend/Dockerfile.development
      context: .
    tty: true
    stdin_open: true
    command: bash -c "go run main.go"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    ports:
      - 8000:8000
    
  frontend:
    image: kawada-tech-blog-front-dev
    container_name: blog-front
    build:
      dockerfile: frontend/Dockerfile.development
      context: .
    tty: true
    stdin_open: true
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
      - backend

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    command: ['server', '/data', '--console-address', ':9001']
    volumes:
      - ./backend/server/minio/data:/data:delegated
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    restart: always
    depends_on:
      - db
      - backend
      - frontend
  
  swagger-ui:
      image: swaggerapi/swagger-ui
      container_name: kawada-tech-blog-swagger-ui
      ports:
        - "80:8080"
      volumes:
        - ./openAPI:/usr/share/nginx/html/openAPI
      environment:
        API_URL: openAPI/main.yml
      depends_on:
        - db
        - backend
        - frontend
        - minio

  swagger-api:
    image: stoplight/prism:latest
    container_name: kawada-tech-blog-swagger-api
    ports:
      - "4010:4010"
    command: mock -h 0.0.0.0 /openAPI/main.yml
    volumes:
      - ./openAPI:/openAPI
    depends_on:
      - db
      - backend
      - frontend
      - minio
      - swagger-ui