openapi: "3.0.3"

info:
  title: "Fuji Blog Server"
  description: "ブログシステム API定義書"
  license:
    name: "MIT License"
    url: "https://opensource.org/license/MIT"
  version: "1.0.0"

servers:
  - url: "http://localhost:8080"
    description: "ローカル環境"
# - url: ""
#   description: "本番環境"

tags:
  - name: admin
    description: "Admin機能"
  - name: public
    description: "公開側機能"

# JWT認証
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Credentials or access token for API

paths:

  "/login":
    post:
      summary: "ログインする"
      tags: ["admin"]
      deprecated: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas/admin.yml#/components/schemas/Admin"
            examples:
              Post:
                $ref: "./components/examples/admin.yml#/components/examples/Admin"
      responses:
        "400":
          $ref: "./components/responses/error.yml#/components/responses/400-BadRequest"

  "/admin/{userID}":
    parameters:
      - name: userID
        in: path
        required: true
        schema: { type: integer }
        example: 1

    get:
      summary: "ユーザー詳細を返す"
      tags: ["admin"]
      deprecated: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "./components/schemas/admin.yml#/components/schemas/Admin"
              examples:
                Post:
                  $ref: "./components/examples/admin.yml#/components/examples/Admin"
        "401":
          $ref: "./components/responses/error.yml#/components/responses/401-Unauthenticated"
        "404":
          $ref: "./components/responses/error.yml#/components/responses/404-NotFound"

    patch:
      summary: "ユーザーを更新する"
      tags: ["admin"]
      deprecated: false
      responses:
        "401":
          $ref: "./components/responses/error.yml#/components/responses/401-Unauthenticated"
        "404":
          $ref: "./components/responses/error.yml#/components/responses/404-NotFound"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas/admin.yml#/components/schemas/Admin"
            examples:
              Post:
                $ref: "./components/examples/admin.yml#/components/examples/Admin"

  "/admin/posts":
    get:
      summary: "ブログ一覧を返す"
      tags: ["admin"]
      deprecated: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "./components/schemas/post.yml#/components/schemas/Posts"
              examples:
                Posts:
                  $ref: "./components/examples/post.yml#/components/examples/Posts"
        "401":
          $ref: "./components/responses/error.yml#/components/responses/401-Unauthenticated"

    post:
      summary: "ブログを登録する"
      tags: ["admin"]
      deprecated: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas/post.yml#/components/schemas/Post"
            examples:
              Post:
                $ref: "./components/examples/post.yml#/components/examples/Post"
      responses:
        "400":
          $ref: "./components/responses/error.yml#/components/responses/400-BadRequest"
        "401":
          $ref: "./components/responses/error.yml#/components/responses/401-Unauthenticated"

  "/admin/posts/{postID}":
    parameters:
      - name: postID
        in: path
        required: true
        schema: { type: integer }
        example: 1

    get:
      summary: "ブログ詳細を返す"
      tags: ["admin"]
      deprecated: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "./components/schemas/post.yml#/components/schemas/Post"
              examples:
                Post:
                  $ref: "./components/examples/post.yml#/components/examples/Post"
        "401":
          $ref: "./components/responses/error.yml#/components/responses/401-Unauthenticated"
        "404":
          $ref: "./components/responses/error.yml#/components/responses/404-NotFound"
    
    patch:
      summary: "ブログを更新する"
      tags: ["admin"]
      deprecated: false
      responses:
        "401":
          $ref: "./components/responses/error.yml#/components/responses/401-Unauthenticated"
        "404":
          $ref: "./components/responses/error.yml#/components/responses/404-NotFound"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas/post.yml#/components/schemas/Post"
            examples:
              Post:
                $ref: "./components/examples/post.yml#/components/examples/Post"

    delete:
      summary: "ブログを削除する"
      tags: ["admin"]
      responses:
        "401":
          $ref: "./components/responses/error.yml#/components/responses/401-Unauthenticated"
        "404":
          $ref: "./components/responses/error.yml#/components/responses/404-NotFound"
  
  "/admin/tags":
    post:
      summary: "タグを作成する"
      tags: ["admin"]
      deprecated: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas/tag.yml#/components/schemas/Tag"
            examples:
              Post:
                $ref: "./components/examples/tag.yml#/components/examples/Tag"
      responses:
        "400":
          $ref: "./components/responses/error.yml#/components/responses/400-BadRequest"
        "401":
          $ref: "./components/responses/error.yml#/components/responses/401-Unauthenticated"

  "/posts":
    get:
      summary: "ブログ一覧を返す"
      tags: ["public"]
      deprecated: false
      parameters:
        - in: query
          name: title
          required: false
        - in: query
          name: tag_name
          required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "./components/schemas/post.yml#/components/schemas/Posts"
              examples:
                Posts:
                  $ref: "./components/examples/post.yml#/components/examples/Posts"
        "401":
          $ref: "./components/responses/error.yml#/components/responses/401-Unauthenticated"

  "/posts/{postID}":
    parameters:
      - name: postID
        in: path
        required: true
        schema: { type: integer }
        example: 1

    get:
      summary: "ブログ詳細を返す"
      tags: ["public"]
      deprecated: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "./components/schemas/admin.yml#/components/schemas/Post"
              examples:
                Post:
                  $ref: "./components/examples/admin.yml#/components/examples/Post"
        "401":
          $ref: "./components/responses/error.yml#/components/responses/401-Unauthenticated"
        "404":
          $ref: "./components/responses/error.yml#/components/responses/404-NotFound"
  
  "/tags":
    get:
      summary: "タグ一覧を返す"
      tags: ["public"]
      deprecated: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "./components/schemas/tag.yml#/components/schemas/Tags"
              examples:
                Posts:
                  $ref: "./components/examples/tag.yml#/components/examples/Tags"
        "401":
          $ref: "./components/responses/error.yml#/components/responses/401-Unauthenticated"