openapi: "3.0.3"

info:
  title: "Admin Example"
  description: |
    - Admin Example
  version: "1.0.0"

paths: {}

components:
  examples:
    Admin:
      summary: 'Admin'
      value:
        id: 1
        name: 'admin1'
        email: 'admin@example.com'
        password: 'password'
        password_confirmation: 'password'
        created_at: '2021-08-25T05:18:29.546Z'
        updated_at: '2021-08-25T05:18:29.546Z'

    AdminIndex:
      summary: 'Admin一覧'
      value:
        - id: 2
          name: 'admin1'
          email: 'admin1@example.com'
          created_at: '2021-08-25T05:18:29.546Z'
          updated_at: '2021-08-25T05:18:29.546Z'
        - id: 1
          name: 'admin2'
          email: 'admin2@example.com'
          created_at: '2021-08-25T05:18:29.546Z'
          updated_at: '2021-08-25T05:18:29.546Z'