openapi: "3.0.3"

info:
  title: "Tag Example"
  description: |
    - Tag Example
  version: "1.0.0"

paths: {}

components:
  examples:
    Tag:
      summary: 'タグ'
      value:
        id: 1
        name: Swagger
        post_id: 1
        created_at: '2021-08-25T05:18:29.546Z'
        updated_at: '2021-08-25T05:18:29.546Z'

    Tags:
      summary: 'タグ一覧'
      value:
        - id: 1
          name: Swagger
          post_id: 1
          created_at: '2021-08-25T05:18:29.546Z'
          updated_at: '2021-08-25T05:18:29.546Z'
        - id: 2
          name: NextJS
          post_id: 1
          created_at: '2021-08-25T05:18:29.546Z'
          updated_at: '2021-08-25T05:18:29.546Z'